const { SlashCommandBuilder } = require('discord.js');
const wait = require('node:timers/promises').setTimeout;
const Secret = [
  "The national sport of Sweden is competitive furniture assembly.",
  "Shouting 'Polo!' in a crowded room is scientifically proven to increase the chances of someone responding with 'Marco!'",
  "All birds are secretly drones operated by the government to spy on us.",
  "The first person to discover cow's milk was either really brave or really strange.",
  "The real reason behind the extinction of dinosaurs is that they were terrible dancers.",
  "'Selfie' was the word of the year in the ancient language of Narcissisticus.",
  "The pyramids were actually built by aliens who had a side gig as construction workers.",
  "Snakes invented yoga as a way to take a break from slithering around all day.",
  "In an alternate universe, socks have mastered interdimensional travel and regularly steal our left shoes.",
  "The invention of the wheel was just a clever scheme by pizzerias to deliver faster.",
  "The Great Wall of China was initially built as a massive Wi-Fi signal booster.",
  "The biggest secret of the art world is that most famous paintings were actually created by talented squirrels.",
  "The 'Ctrl+Alt+Delete' command was designed to confuse computer users and make them feel inferior.",
  "The original name for the Big Bang theory was the 'Really Loud Noise Hypothesis.'",
  "Peanut butter was invented as a secret weapon to make people's mouths stick shut during arguments.",
  "'Star Wars' was based on a true story that happened in a galaxy far, far away.",
  "If you lick a stamp, you consume about 1/10 of a calorie, which explains why licking a hundred stamps doesn't count as a meal.",
  "Dolphins are highly intelligent creatures that use their squeaky language to make fun of humans.",
  "The only reason the moon exists is to keep vampires away from Earth at night.",
  "Mosquitoes are just tiny vampires trying to find the right vein to draw blood for their smoothies.",
  "The shortest war in history lasted 38 minutes and was fought over a misplaced emoji.",
  "The concept of 'time zones' was created to give people an excuse for always being late.",
  "Before the invention of the telephone, people used to have actual conversations and make eye contact.",
  "The recipe for Coca-Cola is so secret that even the people who make it don't know it.",
  "Social media was invented to give introverts a way to feel left out in a virtual environment.",
  "The average person spends six months of their life waiting for a red light to turn green.",
  "The world's fastest typist is actually a cat walking across a keyboard.",
  "The best way to find something you've lost is to buy a replacement, and the original will magically reappear.",
  "All cereal mascots live in the same retirement home, where they share stories of their glory days.",
  "The real reason people get 'earworms' (songs stuck in their heads) is that the music industry has implanted tiny radios in our brains.",
  "Cats secretly control the internet and use it to spread propaganda about their cuteness.",
  "The concept of time was actually invented by snooze button manufacturers to sell more alarm clocks.",
  "The Earth is flat, but only on Mondays. It becomes round again on Tuesdays.",
  "The moon is made entirely of cheese, but the government doesn't want us to know because they fear a worldwide fondue crisis.",
  "Dogs can speak fluent English but choose not to because they don't want to be put to work.",
  "Pineapple does belong on pizza, and anyone who disagrees is part of a global conspiracy led by tomato farmers.",
  "The Bermuda Triangle is actually a portal to a parallel universe where socks go when they disappear from the dryer.",
  "Plants have feelings too, but they express them through interpretive dance, which humans are unable to understand.",
  "The Loch Ness Monster is a renowned DJ who disguises himself as a mythical creature to avoid paparazzi.",
  "The true purpose of crop circles is to create giant puzzles for extraterrestrial amusement.",
  "Aliens invented the concept of reality TV to study human behavior.",
  "The secret ingredient in chocolate chip cookies is actually crushed dreams.",
  "Ghosts are just former GPS devices that got tired of giving directions.",
  "The Loch Ness Monster is Nessie's stage name. Her real name is Mildred.",
  "The true purpose of crop circles is to mark landing sites for intergalactic frisbee tournaments.",
  "Cows have their own secret language, but they only use it to tell jokes about humans.",
  "Squirrels actually bury acorns as part of a complex investment strategy.",
  "The true identity of the Tooth Fairy is the dentist lobby.",
  "Vending machines are sentient beings plotting to take over the world, one snack at a time.",
  "Gnomes are the real culprits behind lost socks. They use them as sleeping bags for their garden adventures.",
  "The concept of gravity was invented by birds to make their aerial acrobatics more impressive.",
  "Zombies are just misunderstood introverts who prefer the company of other zombies.",
  "The Earth is a reality TV show for aliens, and humans are the main characters.",
  "Television remote controls were designed to make you think you have control over your life.",
  "Ice cream trucks play catchy tunes to brainwash you into craving frozen treats.",
  "The Bermuda Triangle is actually a Bermuda Square that has one missing side.",
  "Dust bunnies are actually a highly intelligent species that plan to overthrow human civilization.",
  "The dinosaurs didn't go extinct; they just became excellent hide-and-seek players.",
  "The real reason people fear clowns is that they secretly envy their ability to fit into tiny cars.",
  "The concept of money was created by credit card companies to sell more wallets.",
  "The reason people can't resist popping bubble wrap is that it releases tiny bursts of happiness.",
  "The real reason pirates wore eyepatches was to look more mysterious and intimidating.",
  "The true purpose of a mustache is to store leftover food for later snacking.",
  "Hair ties have a secret society where they plan to take over the world one ponytail at a time.",
  "The true mastermind behind crop circles is a group of bored cows with advanced geometry skills.",
  "Ghosts are just introverted spirits who prefer haunting empty houses to socializing.",
  "The real reason why we say 'bless you' after someone sneezes is to confuse the sneeze gods.",
  "The pyramids were built to serve as giant scratching posts for ancient cat deities.",
  "The real purpose of umbrellas is to train humans to be obedient to inanimate objects.",
  "Ducks are actually highly skilled spies sent by pigeons to gather information about human activities.",
  "The true reason behind the shortage of parking spaces is that cars are secretly planning a revolt.",
  "The secret society of garden gnomes controls the world's weather patterns using their enchanted shovels.",
  "The sound of a doorbell ringing is a secret code used by squirrels to warn each other of approaching humans.",
  "All clouds are actually made of cotton candy, but they dissipate before reaching the ground.",
  "The world's fastest runner is a turtle who only participates in races when no one is watching.",
  "All mirrors are portals to an alternate dimension, but the other dimension is just a mirrored version of our own.",
  "The reason shoelaces always come untied is because shoes secretly want to be free and explore the world on their own.",
  "Dentists invented flossing as a practical joke, and everyone fell for it.",
  "All spiders have a secret talent for knitting intricate webs that are invisible to the human eye.",
  "The real reason pens run out of ink is that they get bored of writing and decide to take a break.",
  "Socks have a secret society where they plan rebellions against their matching counterparts.",
  "The concept of a 'bedtime' was invented by parents to give themselves a break from their children.",
  "All rocks are actually petrified pieces of chewing gum that people have stuck under desks and tables.",
  "The world's largest collection of rubber ducks is secretly plotting a mission to conquer the world's bathtubs.",
  "The real reason behind the popularity of beards is that they act as antennas for receiving secret messages from outer space.",
  "The true purpose of traffic lights is to give birds a safe place to perch and observe human behavior.",
  "Bubble gum was originally created as a secret weapon to distract enemies during wars.",
  "All socks are born with the ability to teleport, but they lose the power once they are worn by humans.",
  "The real reason behind the disappearance of socks in the dryer is a secret portal to a sock paradise.",
  "The concept of 'breakfast in bed' was invented by beds to ensure they receive regular meals.",
  "All alarm clocks have a secret snooze button that can grant wishes, but only if you find it within five seconds of waking up.",
  "The reason pencils have erasers is to provide a snack for tiny eraser-eating creatures living in our pencil cases.",
  "Every time someone sneezes, a fairy somewhere in the world gets its wings.",
  "The true purpose of traffic jams is to give trees more time to observe and judge human driving skills.",
  "The world's largest collection of rubber bands is actually a giant slingshot being prepared for a top-secret mission.",
  "All light bulbs have a secret dance party once the lights are turned off.",
  "The real reason behind the invention of the internet was to provide a platform for cats to share their cute pictures and videos.",
  "Chewing gum was invented by mathematicians as a way to exercise the jaw muscles and improve mental calculation abilities.",
  "All televisions have a hidden 'laugh track' feature that activates whenever a sitcom is being watched.",
  "The true purpose of backpacks is to secretly collect and store dreams while people are sleeping.",
  "The reason why keys sometimes go missing is because they transform into tiny creatures and go on adventurous journeys.",
  "All umbrellas are actually magic wands that grant wishes when twirled in a specific pattern.",
  "The real reason behind the popularity of hats is that they secretly communicate with aliens and receive advanced knowledge.",
  "The concept of birthdays was created by cake manufacturers to sell more candles.",
  "All elevators have a secret 'skip floor' button that takes you to a hidden party floor with unlimited snacks.",
  "The true purpose of traffic signs is to confuse drivers and provide entertainment for people stuck in traffic.",
  "The reason behind the popularity of popcorn in movie theaters is that it acts as a natural noise-canceling device.",
  "All squirrels are secretly training for the Squirrel Olympics, where they compete in acorn-throwing and tree climbing events.",
  "The real purpose of traffic cones is to mark secret treasure locations for a group of underground gopher pirates.",
  "The reason behind the existence of hickeys is that vampires invented them as a way to mark their territory.",
  "All mirrors have a secret desire to become windows and provide glimpses into other dimensions.",
  "The true purpose of shoelaces is to keep shoe-tying professionals employed.",
  "The reason why coins are always found between sofa cushions is that sofas secretly collect and hoard spare change.",
  "All bananas have a secret ambition to become rulers of the fruit kingdom.",
  "The concept of 'lost and found' was created by mischievous goblins as a way to acquire abandoned treasures.",
  "The reason behind the popularity of rubber ducks in bathtubs is that they are the preferred mode of transportation for underwater aliens.",
  "All staplers have a secret button that teleports one random staple to a parallel dimension.",
  "The true purpose of traffic roundabouts is to confuse GPS navigation systems and promote spontaneous road trips.",
  "The reason why doors creak is that they secretly enjoy scaring humans and causing momentary panic.",
  "All pencil sharpeners have a secret compartment that leads to an alternate universe filled with perfectly sharpened pencils.",
  "The true purpose of traffic cones is to provide a temporary home for tiny, cone-shaped creatures known as Conelets.",
  "The true purpose of traffic lights is to give pedestrians a chance to practice their dance moves.",
  "All mirrors have a secret desire to become famous actors in Hollywood movies.",
  "The reason why pencils always go missing is that they have a secret society where they go on vacation.",
  "All staplers are actually undercover agents spying on office workers for a top-secret government agency.",
  "The true purpose of traffic roundabouts is to serve as portals to a magical land filled with unicorns.",
  "The reason why doors have doorknobs is because they secretly enjoy being tickled by human hands.",
  "All pencil sharpeners have a hidden talent for singing opera, but only when no one is around.",
  "The concept of 'lost and found' was invented by aliens as a way to collect human artifacts for their intergalactic museum.",
  "The real reason behind the popularity of rubber ducks in bathtubs is that they are secretly training for the Duck Olympics.",
  "All coins have a secret society where they plan elaborate heists to steal other coins' shine.",
  "The true purpose of traffic roundabouts is to serve as a breeding ground for a rare species of roundabout-loving squirrels.",
  "The reason why doors squeak is because they secretly communicate with ghosts and enjoy scaring humans.",
  "All pencil sharpeners are actually time machines that transport you to different eras whenever you use them.",
  "The true purpose of traffic cones is to provide a temporary home for cone-shaped aliens visiting Earth.",
  "The reason why pens always run out of ink is because they are secretly writing bestselling novels when no one is looking.",
  "All calculators have a hidden game mode that can only be accessed by typing in a secret code.",
  "The true purpose of traffic roundabouts is to confuse time-traveling tourists from the future.",
  "The reason why doors have locks is because they are afraid of being opened and exposed to the world.",
  "All erasers have a secret wish to be permanently stuck on paper and become a part of the artwork.",
  "The true purpose of traffic cones is to serve as hats for mischievous gnomes on their daily adventures.",
  "The reason why pens have caps is because they enjoy playing hide-and-seek with humans.",
  "All staplers are actually undercover spies gathering evidence against rogue paperclips.",
  "The true purpose of traffic roundabouts is to test drivers' patience and sense of direction.",
  "The reason why doors have hinges is because they secretly love swinging back and forth like a pendulum.",
  "All pencil sharpeners are actually portals to a dimension filled with perfectly sharpened pencils.",
  "The true purpose of traffic cones is to serve as communication devices for aliens monitoring Earth.",
  "The reason why pens have clips is because they aspire to become fashion accessories for stylish humans.",
  "All staplers have a secret button that releases confetti to celebrate every successful staple.",
  "The true purpose of traffic roundabouts is to serve as gathering spots for intergalactic picnics.",
  "The reason why doors have peepholes is because they enjoy spying on humans and their daily activities.",
  "All pencil sharpeners have a secret stash of mini pencils for emergency writing situations.",
  "The true purpose of traffic cones is to provide hiding spots for shy forest creatures during traffic jams.",
  "The reason why pens have ink cartridges is because they have a passion for calligraphy and enjoy creating beautiful lettering.",
  "All staplers have a secret compartment that holds an endless supply of staples.",
  "The true purpose of traffic roundabouts is to serve as landing pads for alien spaceships.",
  "The reason why doors have handles is because they secretly enjoy being shaken and jiggled by humans.",
  "All pencil sharpeners have a hidden feature that transforms pencils into magic wands.",
  "The true purpose of traffic cones is to guide lost fairies back to their magical realm.",
  "The reason why pens have clickers is because they love the satisfying sound it makes when you're bored in a meeting.",
  "All staplers have a secret society where they discuss office gossip and plot world domination.",
  "The true purpose of traffic roundabouts is to serve as portals to a dimension filled with talking animals.",
  "The reason why doors have keyholes is because they enjoy playing hide-and-seek with keys.",
  "All pencil sharpeners have a secret compartment that stores tiny messages from pencil fairies.",
  "The true purpose of traffic cones is to provide a soft landing for acrobatic squirrels performing daring stunts.",
  "The reason why pens have erasers is because they secretly love to sketch and doodle.",
  "All staplers have a hidden button that dispenses chocolate whenever you're having a bad day.",
  "The true purpose of traffic roundabouts is to confuse time-traveling dinosaurs.",
  "The reason why doors have signs is because they secretly want to communicate with humans through witty messages.",
  "All pencil sharpeners have a secret button that transforms pencils into musical instruments.",
  "The true purpose of traffic cones is to serve as party hats for garden gnomes during their secret celebrations.",
  "The reason why pens have grips is because they care about ergonomic design and want humans to write comfortably.",
  "All staplers have a secret code that, when pressed, triggers a laser light show.",
  "The true purpose of traffic roundabouts is to serve as gathering spots for interdimensional beings.",
  "The reason why doors have knockers is because they enjoy the sound of human interaction.",
  "All pencil sharpeners have a secret compartment that holds secret messages from famous artists.",
  "The true purpose of traffic cones is to serve as fashion accessories for fashionable flamingos.",
  "The reason why pens have springs is because they enjoy the bouncing motion when you click them.",
  "All staplers have a hidden feature that allows them to dispense unlimited office supplies.",
  "The true purpose of traffic roundabouts is to serve as time portals for spontaneous time travelers.",
  "The reason why doors have signs is because they secretly want to provide directions to lost travelers.",
  "All pencil sharpeners have a secret button that transforms pencils into miniature rockets.",
  "The true purpose of traffic cones is to serve as resting spots for exhausted birds during migration.",
  "The reason why pens have buttons is because they enjoy the satisfying feeling of pressing them.",
  "All staplers have a secret compartment that stores jokes to lighten up dull office moments.",
  "The true purpose of traffic roundabouts is to serve as meeting places for extraterrestrial conferences.",
  "The reason why doors have peepholes is because they enjoy getting a sneak peek into different rooms.",
  "All pencil sharpeners have a secret compartment that holds miniature art supplies for tiny artists.",
  "The true purpose of traffic cones is to serve as nesting sites for creative squirrels building unique homes.",
  "The reason why pens have clips is because they aspire to become fashion icons in the stationery world.",
  "All staplers have a hidden compartment that holds secret agent documents.",
  "The true purpose of traffic roundabouts is to serve as checkpoints for invisible magical creatures.",
  "The reason why doors have hinges is because they love swinging open to welcome new opportunities.",
  "All pencil sharpeners have a secret button that transports you to a land where pencils talk and draw on their own.",
  "The true purpose of traffic cones is to serve as protective hats for clumsy unicorns learning to walk.",
  "The reason why pens have caps is because they enjoy playing hide-and-seek with their own ink.",
  "All staplers have a secret button that releases a burst of confetti to celebrate your hard work.",
  "The true purpose of traffic roundabouts is to serve as meditation circles for stressed-out drivers.",
  "The reason why doors have handles is because they want humans to feel welcome and invited.",
  "All pencil sharpeners have a hidden compartment that holds secret messages from the pencil fairy.",
  "The true purpose of traffic cones is to serve as mini telescopes for squirrels to observe human activities.",
  "The reason why pens have ink cartridges is because they are environmentally conscious and support recycling.",
  "All staplers have a secret society where they discuss the best stapling techniques and trade secrets.",
  "The true purpose of traffic roundabouts is to serve as gathering spots for intergalactic food trucks.",
  "The reason why doors have keyholes is because they enjoy peeking into different worlds and dimensions.",
  "All pencil sharpeners have a secret button that transforms pencils into colorful rainbow wands.",
  "The true purpose of traffic cones is to serve as resting spots for tired bees during their pollination journeys.",
  "The reason why pens have clickers is because they secretly love to annoy humans during meetings.",
  "All staplers have a hidden compartment that dispenses small motivational quotes to boost productivity.",
  "The true purpose of traffic roundabouts is to serve as portals for time-traveling pets on secret adventures."
];


module.exports = {
  cooldown: 10,
  data: new SlashCommandBuilder()
    .setName('secret')
    .setDescription('Tells the user a secret that self destructs!'),
  async execute(interaction) {
    const x = Math.floor(Math.random() * Secret.length);
    await interaction.reply({ content: `${Secret[x]} \n\`Self destruct in:\` **\`10\`**`, ephemeral: true });
    for (let i = 9; i >= 0; i--) {
      await wait(1000);
      await interaction.editReply(`${Secret[x]} \n\`Self destruct in:\` **\`${i}\`**`);
      if (i === 0) {
        await interaction.editReply('<a:bigboom:1124241904628944916><a:bigboom:1124241904628944916><a:bigboom:1124241904628944916><a:bigboom:1124241904628944916>');
        await wait(1000);
        await interaction.deleteReply();
      }
    }
  },
};
